alert("External Usul");

let name = "bunyod kot";

console.log(name);

console.log(number);

let number = 10;

const borderColor = "red";

console.log(borderColor);

const person={
   name: "bunyod kot";
}


person.name = "bexa";

console.log(person.name);

console.log(isMarried);

console.log(clientAge)

let undefined;

console.log(undefined);


const car = {
    type:"Chevrolet",
    name:"Mers",
    position: 4,
    color: "Black",
    isElectric: true,
}

console.log(car)
console.log(car['type'])

car.isElectric = false